/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TestnetFaucetApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TestnetFaucetApiTests
    {
        private TestnetFaucetApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TestnetFaucetApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TestnetFaucetApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TestnetFaucetApi
            //Assert.IsInstanceOfType(typeof(TestnetFaucetApi), instance, "instance is a TestnetFaucetApi");
        }

        
        /// <summary>
        /// Test TestnetGetFaucet
        /// </summary>
        [Test]
        public void TestnetGetFaucetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //decimal? amount = null;
            //var response = instance.TestnetGetFaucet(address, amount);
            //Assert.IsInstanceOf<GetFaucetResponse> (response, "response is GetFaucetResponse");
        }
        
    }

}
