/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BurnTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BurnTokenRequestTests
    {
        // TODO uncomment below to declare an instance variable for BurnTokenRequest
        //private BurnTokenRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BurnTokenRequest
            //instance = new BurnTokenRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BurnTokenRequest
        /// </summary>
        [Test]
        public void BurnTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BurnTokenRequest
            //Assert.IsInstanceOfType<BurnTokenRequest> (instance, "variable 'instance' is a BurnTokenRequest");
        }


        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Transfer'
        /// </summary>
        [Test]
        public void TransferTest()
        {
            // TODO unit test for the property 'Transfer'
        }
        /// <summary>
        /// Test the property 'Burn'
        /// </summary>
        [Test]
        public void BurnTest()
        {
            // TODO unit test for the property 'Burn'
        }

    }

}
