/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetAddressInfoResponseUtxos
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAddressInfoResponseUtxosTests
    {
        // TODO uncomment below to declare an instance variable for GetAddressInfoResponseUtxos
        //private GetAddressInfoResponseUtxos instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAddressInfoResponseUtxos
            //instance = new GetAddressInfoResponseUtxos();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAddressInfoResponseUtxos
        /// </summary>
        [Test]
        public void GetAddressInfoResponseUtxosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAddressInfoResponseUtxos
            //Assert.IsInstanceOfType<GetAddressInfoResponseUtxos> (instance, "variable 'instance' is a GetAddressInfoResponseUtxos");
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Txid'
        /// </summary>
        [Test]
        public void TxidTest()
        {
            // TODO unit test for the property 'Txid'
        }
        /// <summary>
        /// Test the property 'Blockheight'
        /// </summary>
        [Test]
        public void BlockheightTest()
        {
            // TODO unit test for the property 'Blockheight'
        }
        /// <summary>
        /// Test the property 'Blocktime'
        /// </summary>
        [Test]
        public void BlocktimeTest()
        {
            // TODO unit test for the property 'Blocktime'
        }
        /// <summary>
        /// Test the property 'ScriptPubKey'
        /// </summary>
        [Test]
        public void ScriptPubKeyTest()
        {
            // TODO unit test for the property 'ScriptPubKey'
        }
        /// <summary>
        /// Test the property 'Used'
        /// </summary>
        [Test]
        public void UsedTest()
        {
            // TODO unit test for the property 'Used'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Test]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

    }

}
