/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetAddressInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAddressInfoResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetAddressInfoResponse
        //private GetAddressInfoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAddressInfoResponse
            //instance = new GetAddressInfoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAddressInfoResponse
        /// </summary>
        [Test]
        public void GetAddressInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAddressInfoResponse
            //Assert.IsInstanceOfType<GetAddressInfoResponse> (instance, "variable 'instance' is a GetAddressInfoResponse");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Utxos'
        /// </summary>
        [Test]
        public void UtxosTest()
        {
            // TODO unit test for the property 'Utxos'
        }

    }

}
