/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetAddressUnconfirmedBalanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAddressUnconfirmedBalanceResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetAddressUnconfirmedBalanceResponse
        //private GetAddressUnconfirmedBalanceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAddressUnconfirmedBalanceResponse
            //instance = new GetAddressUnconfirmedBalanceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAddressUnconfirmedBalanceResponse
        /// </summary>
        [Test]
        public void GetAddressUnconfirmedBalanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAddressUnconfirmedBalanceResponse
            //Assert.IsInstanceOfType<GetAddressUnconfirmedBalanceResponse> (instance, "variable 'instance' is a GetAddressUnconfirmedBalanceResponse");
        }



    }

}
