/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetBlockResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetBlockResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetBlockResponse
        //private GetBlockResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetBlockResponse
            //instance = new GetBlockResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetBlockResponse
        /// </summary>
        [Test]
        public void GetBlockResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetBlockResponse
            //Assert.IsInstanceOfType<GetBlockResponse> (instance, "variable 'instance' is a GetBlockResponse");
        }


        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Confirmations'
        /// </summary>
        [Test]
        public void ConfirmationsTest()
        {
            // TODO unit test for the property 'Confirmations'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Merkleroot'
        /// </summary>
        [Test]
        public void MerklerootTest()
        {
            // TODO unit test for the property 'Merkleroot'
        }
        /// <summary>
        /// Test the property 'Tx'
        /// </summary>
        [Test]
        public void TxTest()
        {
            // TODO unit test for the property 'Tx'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'Bits'
        /// </summary>
        [Test]
        public void BitsTest()
        {
            // TODO unit test for the property 'Bits'
        }
        /// <summary>
        /// Test the property 'Difficulty'
        /// </summary>
        [Test]
        public void DifficultyTest()
        {
            // TODO unit test for the property 'Difficulty'
        }
        /// <summary>
        /// Test the property 'Previousblockhash'
        /// </summary>
        [Test]
        public void PreviousblockhashTest()
        {
            // TODO unit test for the property 'Previousblockhash'
        }
        /// <summary>
        /// Test the property 'Nextblockhash'
        /// </summary>
        [Test]
        public void NextblockhashTest()
        {
            // TODO unit test for the property 'Nextblockhash'
        }
        /// <summary>
        /// Test the property 'Reward'
        /// </summary>
        [Test]
        public void RewardTest()
        {
            // TODO unit test for the property 'Reward'
        }

    }

}
