/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetBlockIndexResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetBlockIndexResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetBlockIndexResponse
        //private GetBlockIndexResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetBlockIndexResponse
            //instance = new GetBlockIndexResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetBlockIndexResponse
        /// </summary>
        [Test]
        public void GetBlockIndexResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetBlockIndexResponse
            //Assert.IsInstanceOfType<GetBlockIndexResponse> (instance, "variable 'instance' is a GetBlockIndexResponse");
        }


        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Test]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }

    }

}
