/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetFaucetResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetFaucetResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for GetFaucetResponseData
        //private GetFaucetResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetFaucetResponseData
            //instance = new GetFaucetResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetFaucetResponseData
        /// </summary>
        [Test]
        public void GetFaucetResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetFaucetResponseData
            //Assert.IsInstanceOfType<GetFaucetResponseData> (instance, "variable 'instance' is a GetFaucetResponseData");
        }


        /// <summary>
        /// Test the property 'TxId'
        /// </summary>
        [Test]
        public void TxIdTest()
        {
            // TODO unit test for the property 'TxId'
        }

    }

}
