/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTokenMetadataResponseMetadataOfIssuanceData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTokenMetadataResponseMetadataOfIssuanceDataTests
    {
        // TODO uncomment below to declare an instance variable for GetTokenMetadataResponseMetadataOfIssuanceData
        //private GetTokenMetadataResponseMetadataOfIssuanceData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTokenMetadataResponseMetadataOfIssuanceData
            //instance = new GetTokenMetadataResponseMetadataOfIssuanceData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTokenMetadataResponseMetadataOfIssuanceData
        /// </summary>
        [Test]
        public void GetTokenMetadataResponseMetadataOfIssuanceDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTokenMetadataResponseMetadataOfIssuanceData
            //Assert.IsInstanceOfType<GetTokenMetadataResponseMetadataOfIssuanceData> (instance, "variable 'instance' is a GetTokenMetadataResponseMetadataOfIssuanceData");
        }


        /// <summary>
        /// Test the property 'TokenName'
        /// </summary>
        [Test]
        public void TokenNameTest()
        {
            // TODO unit test for the property 'TokenName'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Test]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'UserData'
        /// </summary>
        [Test]
        public void UserDataTest()
        {
            // TODO unit test for the property 'UserData'
        }

    }

}
