/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTokenHoldersResponseHolders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTokenHoldersResponseHoldersTests
    {
        // TODO uncomment below to declare an instance variable for GetTokenHoldersResponseHolders
        //private GetTokenHoldersResponseHolders instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTokenHoldersResponseHolders
            //instance = new GetTokenHoldersResponseHolders();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTokenHoldersResponseHolders
        /// </summary>
        [Test]
        public void GetTokenHoldersResponseHoldersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTokenHoldersResponseHolders
            //Assert.IsInstanceOfType<GetTokenHoldersResponseHolders> (instance, "variable 'instance' is a GetTokenHoldersResponseHolders");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

    }

}
