/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTransactionInfoResponseTokens
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTransactionInfoResponseTokensTests
    {
        // TODO uncomment below to declare an instance variable for GetTransactionInfoResponseTokens
        //private GetTransactionInfoResponseTokens instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTransactionInfoResponseTokens
            //instance = new GetTransactionInfoResponseTokens();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTransactionInfoResponseTokens
        /// </summary>
        [Test]
        public void GetTransactionInfoResponseTokensInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTransactionInfoResponseTokens
            //Assert.IsInstanceOfType<GetTransactionInfoResponseTokens> (instance, "variable 'instance' is a GetTransactionInfoResponseTokens");
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Test]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'IssueTxid'
        /// </summary>
        [Test]
        public void IssueTxidTest()
        {
            // TODO unit test for the property 'IssueTxid'
        }
        /// <summary>
        /// Test the property 'Divisibility'
        /// </summary>
        [Test]
        public void DivisibilityTest()
        {
            // TODO unit test for the property 'Divisibility'
        }
        /// <summary>
        /// Test the property 'LockStatus'
        /// </summary>
        [Test]
        public void LockStatusTest()
        {
            // TODO unit test for the property 'LockStatus'
        }
        /// <summary>
        /// Test the property 'AggregationPolicy'
        /// </summary>
        [Test]
        public void AggregationPolicyTest()
        {
            // TODO unit test for the property 'AggregationPolicy'
        }

    }

}
