/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTransactionInfoResponsePreviousOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTransactionInfoResponsePreviousOutputTests
    {
        // TODO uncomment below to declare an instance variable for GetTransactionInfoResponsePreviousOutput
        //private GetTransactionInfoResponsePreviousOutput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTransactionInfoResponsePreviousOutput
            //instance = new GetTransactionInfoResponsePreviousOutput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTransactionInfoResponsePreviousOutput
        /// </summary>
        [Test]
        public void GetTransactionInfoResponsePreviousOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTransactionInfoResponsePreviousOutput
            //Assert.IsInstanceOfType<GetTransactionInfoResponsePreviousOutput> (instance, "variable 'instance' is a GetTransactionInfoResponsePreviousOutput");
        }


        /// <summary>
        /// Test the property 'Asm'
        /// </summary>
        [Test]
        public void AsmTest()
        {
            // TODO unit test for the property 'Asm'
        }
        /// <summary>
        /// Test the property 'Hex'
        /// </summary>
        [Test]
        public void HexTest()
        {
            // TODO unit test for the property 'Hex'
        }
        /// <summary>
        /// Test the property 'ReqSigs'
        /// </summary>
        [Test]
        public void ReqSigsTest()
        {
            // TODO unit test for the property 'ReqSigs'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Test]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }

    }

}
