/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTransactionInfoResponseVin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTransactionInfoResponseVinTests
    {
        // TODO uncomment below to declare an instance variable for GetTransactionInfoResponseVin
        //private GetTransactionInfoResponseVin instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTransactionInfoResponseVin
            //instance = new GetTransactionInfoResponseVin();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTransactionInfoResponseVin
        /// </summary>
        [Test]
        public void GetTransactionInfoResponseVinInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTransactionInfoResponseVin
            //Assert.IsInstanceOfType<GetTransactionInfoResponseVin> (instance, "variable 'instance' is a GetTransactionInfoResponseVin");
        }


        /// <summary>
        /// Test the property 'Txid'
        /// </summary>
        [Test]
        public void TxidTest()
        {
            // TODO unit test for the property 'Txid'
        }
        /// <summary>
        /// Test the property 'Vout'
        /// </summary>
        [Test]
        public void VoutTest()
        {
            // TODO unit test for the property 'Vout'
        }
        /// <summary>
        /// Test the property 'ScriptSig'
        /// </summary>
        [Test]
        public void ScriptSigTest()
        {
            // TODO unit test for the property 'ScriptSig'
        }
        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [Test]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }
        /// <summary>
        /// Test the property 'PreviousOutput'
        /// </summary>
        [Test]
        public void PreviousOutputTest()
        {
            // TODO unit test for the property 'PreviousOutput'
        }
        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Test]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
