/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTxResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTxResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetTxResponse
        //private GetTxResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTxResponse
            //instance = new GetTxResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTxResponse
        /// </summary>
        [Test]
        public void GetTxResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTxResponse
            //Assert.IsInstanceOfType<GetTxResponse> (instance, "variable 'instance' is a GetTxResponse");
        }


        /// <summary>
        /// Test the property 'Txid'
        /// </summary>
        [Test]
        public void TxidTest()
        {
            // TODO unit test for the property 'Txid'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Locktime'
        /// </summary>
        [Test]
        public void LocktimeTest()
        {
            // TODO unit test for the property 'Locktime'
        }
        /// <summary>
        /// Test the property 'Vin'
        /// </summary>
        [Test]
        public void VinTest()
        {
            // TODO unit test for the property 'Vin'
        }
        /// <summary>
        /// Test the property 'Vout'
        /// </summary>
        [Test]
        public void VoutTest()
        {
            // TODO unit test for the property 'Vout'
        }
        /// <summary>
        /// Test the property 'Blocktime'
        /// </summary>
        [Test]
        public void BlocktimeTest()
        {
            // TODO unit test for the property 'Blocktime'
        }
        /// <summary>
        /// Test the property 'Blockheight'
        /// </summary>
        [Test]
        public void BlockheightTest()
        {
            // TODO unit test for the property 'Blockheight'
        }
        /// <summary>
        /// Test the property 'Totalsent'
        /// </summary>
        [Test]
        public void TotalsentTest()
        {
            // TODO unit test for the property 'Totalsent'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Blockhash'
        /// </summary>
        [Test]
        public void BlockhashTest()
        {
            // TODO unit test for the property 'Blockhash'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Confirmations'
        /// </summary>
        [Test]
        public void ConfirmationsTest()
        {
            // TODO unit test for the property 'Confirmations'
        }
        /// <summary>
        /// Test the property 'ValueOut'
        /// </summary>
        [Test]
        public void ValueOutTest()
        {
            // TODO unit test for the property 'ValueOut'
        }
        /// <summary>
        /// Test the property 'ValueIn'
        /// </summary>
        [Test]
        public void ValueInTest()
        {
            // TODO unit test for the property 'ValueIn'
        }
        /// <summary>
        /// Test the property 'Fees'
        /// </summary>
        [Test]
        public void FeesTest()
        {
            // TODO unit test for the property 'Fees'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

    }

}
