/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMetaTests
    {
        // TODO uncomment below to declare an instance variable for GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta
        //private GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta
            //instance = new GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta
        /// </summary>
        [Test]
        public void GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta
            //Assert.IsInstanceOfType<GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta> (instance, "variable 'instance' is a GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
