/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTxResponseVin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTxResponseVinTests
    {
        // TODO uncomment below to declare an instance variable for GetTxResponseVin
        //private GetTxResponseVin instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTxResponseVin
            //instance = new GetTxResponseVin();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTxResponseVin
        /// </summary>
        [Test]
        public void GetTxResponseVinInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTxResponseVin
            //Assert.IsInstanceOfType<GetTxResponseVin> (instance, "variable 'instance' is a GetTxResponseVin");
        }


        /// <summary>
        /// Test the property 'Txid'
        /// </summary>
        [Test]
        public void TxidTest()
        {
            // TODO unit test for the property 'Txid'
        }
        /// <summary>
        /// Test the property 'Vout'
        /// </summary>
        [Test]
        public void VoutTest()
        {
            // TODO unit test for the property 'Vout'
        }
        /// <summary>
        /// Test the property 'ScriptSig'
        /// </summary>
        [Test]
        public void ScriptSigTest()
        {
            // TODO unit test for the property 'ScriptSig'
        }
        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [Test]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'ValueSat'
        /// </summary>
        [Test]
        public void ValueSatTest()
        {
            // TODO unit test for the property 'ValueSat'
        }
        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Test]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }

    }

}
