/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTokenHoldersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTokenHoldersResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetTokenHoldersResponse
        //private GetTokenHoldersResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTokenHoldersResponse
            //instance = new GetTokenHoldersResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTokenHoldersResponse
        /// </summary>
        [Test]
        public void GetTokenHoldersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTokenHoldersResponse
            //Assert.IsInstanceOfType<GetTokenHoldersResponse> (instance, "variable 'instance' is a GetTokenHoldersResponse");
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Test]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Holders'
        /// </summary>
        [Test]
        public void HoldersTest()
        {
            // TODO unit test for the property 'Holders'
        }
        /// <summary>
        /// Test the property 'Divibility'
        /// </summary>
        [Test]
        public void DivibilityTest()
        {
            // TODO unit test for the property 'Divibility'
        }
        /// <summary>
        /// Test the property 'LockStatus'
        /// </summary>
        [Test]
        public void LockStatusTest()
        {
            // TODO unit test for the property 'LockStatus'
        }
        /// <summary>
        /// Test the property 'AggregationPolicy'
        /// </summary>
        [Test]
        public void AggregationPolicyTest()
        {
            // TODO unit test for the property 'AggregationPolicy'
        }
        /// <summary>
        /// Test the property 'SomeUtxo'
        /// </summary>
        [Test]
        public void SomeUtxoTest()
        {
            // TODO unit test for the property 'SomeUtxo'
        }

    }

}
