/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTransactionInfoResponseVout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTransactionInfoResponseVoutTests
    {
        // TODO uncomment below to declare an instance variable for GetTransactionInfoResponseVout
        //private GetTransactionInfoResponseVout instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTransactionInfoResponseVout
            //instance = new GetTransactionInfoResponseVout();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTransactionInfoResponseVout
        /// </summary>
        [Test]
        public void GetTransactionInfoResponseVoutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTransactionInfoResponseVout
            //Assert.IsInstanceOfType<GetTransactionInfoResponseVout> (instance, "variable 'instance' is a GetTransactionInfoResponseVout");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Test]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }
        /// <summary>
        /// Test the property 'ScriptPubKey'
        /// </summary>
        [Test]
        public void ScriptPubKeyTest()
        {
            // TODO unit test for the property 'ScriptPubKey'
        }
        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Test]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }
        /// <summary>
        /// Test the property 'Used'
        /// </summary>
        [Test]
        public void UsedTest()
        {
            // TODO unit test for the property 'Used'
        }
        /// <summary>
        /// Test the property 'Blockheight'
        /// </summary>
        [Test]
        public void BlockheightTest()
        {
            // TODO unit test for the property 'Blockheight'
        }
        /// <summary>
        /// Test the property 'UsedBlockheight'
        /// </summary>
        [Test]
        public void UsedBlockheightTest()
        {
            // TODO unit test for the property 'UsedBlockheight'
        }
        /// <summary>
        /// Test the property 'UsedTxid'
        /// </summary>
        [Test]
        public void UsedTxidTest()
        {
            // TODO unit test for the property 'UsedTxid'
        }

    }

}
