/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTransactionInfoResponseScriptSig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTransactionInfoResponseScriptSigTests
    {
        // TODO uncomment below to declare an instance variable for GetTransactionInfoResponseScriptSig
        //private GetTransactionInfoResponseScriptSig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTransactionInfoResponseScriptSig
            //instance = new GetTransactionInfoResponseScriptSig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTransactionInfoResponseScriptSig
        /// </summary>
        [Test]
        public void GetTransactionInfoResponseScriptSigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTransactionInfoResponseScriptSig
            //Assert.IsInstanceOfType<GetTransactionInfoResponseScriptSig> (instance, "variable 'instance' is a GetTransactionInfoResponseScriptSig");
        }


        /// <summary>
        /// Test the property 'Asm'
        /// </summary>
        [Test]
        public void AsmTest()
        {
            // TODO unit test for the property 'Asm'
        }
        /// <summary>
        /// Test the property 'Hex'
        /// </summary>
        [Test]
        public void HexTest()
        {
            // TODO unit test for the property 'Hex'
        }

    }

}
