/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTokenMetadataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTokenMetadataResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetTokenMetadataResponse
        //private GetTokenMetadataResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTokenMetadataResponse
            //instance = new GetTokenMetadataResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTokenMetadataResponse
        /// </summary>
        [Test]
        public void GetTokenMetadataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTokenMetadataResponse
            //Assert.IsInstanceOfType<GetTokenMetadataResponse> (instance, "variable 'instance' is a GetTokenMetadataResponse");
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Test]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Divisibility'
        /// </summary>
        [Test]
        public void DivisibilityTest()
        {
            // TODO unit test for the property 'Divisibility'
        }
        /// <summary>
        /// Test the property 'LockStatus'
        /// </summary>
        [Test]
        public void LockStatusTest()
        {
            // TODO unit test for the property 'LockStatus'
        }
        /// <summary>
        /// Test the property 'AggregationPolicy'
        /// </summary>
        [Test]
        public void AggregationPolicyTest()
        {
            // TODO unit test for the property 'AggregationPolicy'
        }
        /// <summary>
        /// Test the property 'TotalSupply'
        /// </summary>
        [Test]
        public void TotalSupplyTest()
        {
            // TODO unit test for the property 'TotalSupply'
        }
        /// <summary>
        /// Test the property 'NumOfHolders'
        /// </summary>
        [Test]
        public void NumOfHoldersTest()
        {
            // TODO unit test for the property 'NumOfHolders'
        }
        /// <summary>
        /// Test the property 'NumOfTransfers'
        /// </summary>
        [Test]
        public void NumOfTransfersTest()
        {
            // TODO unit test for the property 'NumOfTransfers'
        }
        /// <summary>
        /// Test the property 'NumofIssuance'
        /// </summary>
        [Test]
        public void NumofIssuanceTest()
        {
            // TODO unit test for the property 'NumofIssuance'
        }
        /// <summary>
        /// Test the property 'NumOfBurns'
        /// </summary>
        [Test]
        public void NumOfBurnsTest()
        {
            // TODO unit test for the property 'NumOfBurns'
        }
        /// <summary>
        /// Test the property 'FirstBlock'
        /// </summary>
        [Test]
        public void FirstBlockTest()
        {
            // TODO unit test for the property 'FirstBlock'
        }
        /// <summary>
        /// Test the property 'IssuanceTxid'
        /// </summary>
        [Test]
        public void IssuanceTxidTest()
        {
            // TODO unit test for the property 'IssuanceTxid'
        }
        /// <summary>
        /// Test the property 'IssueAddress'
        /// </summary>
        [Test]
        public void IssueAddressTest()
        {
            // TODO unit test for the property 'IssueAddress'
        }
        /// <summary>
        /// Test the property 'MetadataOfIssuance'
        /// </summary>
        [Test]
        public void MetadataOfIssuanceTest()
        {
            // TODO unit test for the property 'MetadataOfIssuance'
        }
        /// <summary>
        /// Test the property 'MetadataOfUtxo'
        /// </summary>
        [Test]
        public void MetadataOfUtxoTest()
        {
            // TODO unit test for the property 'MetadataOfUtxo'
        }

    }

}
