/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IssueTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueTokenResponseTests
    {
        // TODO uncomment below to declare an instance variable for IssueTokenResponse
        //private IssueTokenResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IssueTokenResponse
            //instance = new IssueTokenResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IssueTokenResponse
        /// </summary>
        [Test]
        public void IssueTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IssueTokenResponse
            //Assert.IsInstanceOfType<IssueTokenResponse> (instance, "variable 'instance' is a IssueTokenResponse");
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Test]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'TxHex'
        /// </summary>
        [Test]
        public void TxHexTest()
        {
            // TODO unit test for the property 'TxHex'
        }

    }

}
