/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IssueTokenRequestMetadataRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueTokenRequestMetadataRulesTests
    {
        // TODO uncomment below to declare an instance variable for IssueTokenRequestMetadataRules
        //private IssueTokenRequestMetadataRules instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IssueTokenRequestMetadataRules
            //instance = new IssueTokenRequestMetadataRules();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IssueTokenRequestMetadataRules
        /// </summary>
        [Test]
        public void IssueTokenRequestMetadataRulesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IssueTokenRequestMetadataRules
            //Assert.IsInstanceOfType<IssueTokenRequestMetadataRules> (instance, "variable 'instance' is a IssueTokenRequestMetadataRules");
        }


        /// <summary>
        /// Test the property 'Fees'
        /// </summary>
        [Test]
        public void FeesTest()
        {
            // TODO unit test for the property 'Fees'
        }
        /// <summary>
        /// Test the property 'Holders'
        /// </summary>
        [Test]
        public void HoldersTest()
        {
            // TODO unit test for the property 'Holders'
        }
        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Test]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

    }

}
