/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IssueTokenRequestMetadataRulesFees
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueTokenRequestMetadataRulesFeesTests
    {
        // TODO uncomment below to declare an instance variable for IssueTokenRequestMetadataRulesFees
        //private IssueTokenRequestMetadataRulesFees instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IssueTokenRequestMetadataRulesFees
            //instance = new IssueTokenRequestMetadataRulesFees();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IssueTokenRequestMetadataRulesFees
        /// </summary>
        [Test]
        public void IssueTokenRequestMetadataRulesFeesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IssueTokenRequestMetadataRulesFees
            //Assert.IsInstanceOfType<IssueTokenRequestMetadataRulesFees> (instance, "variable 'instance' is a IssueTokenRequestMetadataRulesFees");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Locked'
        /// </summary>
        [Test]
        public void LockedTest()
        {
            // TODO unit test for the property 'Locked'
        }

    }

}
