/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IssueTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueTokenRequestTests
    {
        // TODO uncomment below to declare an instance variable for IssueTokenRequest
        //private IssueTokenRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IssueTokenRequest
            //instance = new IssueTokenRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IssueTokenRequest
        /// </summary>
        [Test]
        public void IssueTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IssueTokenRequest
            //Assert.IsInstanceOfType<IssueTokenRequest> (instance, "variable 'instance' is a IssueTokenRequest");
        }


        /// <summary>
        /// Test the property 'IssueAddress'
        /// </summary>
        [Test]
        public void IssueAddressTest()
        {
            // TODO unit test for the property 'IssueAddress'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Divisibility'
        /// </summary>
        [Test]
        public void DivisibilityTest()
        {
            // TODO unit test for the property 'Divisibility'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Reissuable'
        /// </summary>
        [Test]
        public void ReissuableTest()
        {
            // TODO unit test for the property 'Reissuable'
        }
        /// <summary>
        /// Test the property 'Flags'
        /// </summary>
        [Test]
        public void FlagsTest()
        {
            // TODO unit test for the property 'Flags'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
