/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IssueTokenRequestMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueTokenRequestMetadataTests
    {
        // TODO uncomment below to declare an instance variable for IssueTokenRequestMetadata
        //private IssueTokenRequestMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IssueTokenRequestMetadata
            //instance = new IssueTokenRequestMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IssueTokenRequestMetadata
        /// </summary>
        [Test]
        public void IssueTokenRequestMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IssueTokenRequestMetadata
            //Assert.IsInstanceOfType<IssueTokenRequestMetadata> (instance, "variable 'instance' is a IssueTokenRequestMetadata");
        }


        /// <summary>
        /// Test the property 'TokenName'
        /// </summary>
        [Test]
        public void TokenNameTest()
        {
            // TODO unit test for the property 'TokenName'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Test]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Test]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }
        /// <summary>
        /// Test the property 'UserData'
        /// </summary>
        [Test]
        public void UserDataTest()
        {
            // TODO unit test for the property 'UserData'
        }
        /// <summary>
        /// Test the property 'Encryptions'
        /// </summary>
        [Test]
        public void EncryptionsTest()
        {
            // TODO unit test for the property 'Encryptions'
        }
        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Test]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }

    }

}
