/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Neblio.API.Client;
using Neblio.API.Model;

namespace Neblio.API.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IJSONRPCApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node
        /// </summary>
        /// <remarks>
        /// Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </remarks>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>RpcResponse</returns>
        RpcResponse RPC (RpcRequest rpcRequest);

        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node
        /// </summary>
        /// <remarks>
        /// Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </remarks>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>ApiResponse of RpcResponse</returns>
        ApiResponse<RpcResponse> RPCWithHttpInfo (RpcRequest rpcRequest);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node
        /// </summary>
        /// <remarks>
        /// Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </remarks>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>Task of RpcResponse</returns>
        System.Threading.Tasks.Task<RpcResponse> RPCAsync (RpcRequest rpcRequest);

        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node
        /// </summary>
        /// <remarks>
        /// Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </remarks>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>Task of ApiResponse (RpcResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RpcResponse>> RPCAsyncWithHttpInfo (RpcRequest rpcRequest);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class JSONRPCApi : IJSONRPCApi
    {
        private Neblio.API.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="JSONRPCApi"/> class.
        /// </summary>
        /// <returns></returns>
        public JSONRPCApi(String basePath)
        {
            this.Configuration = new Neblio.API.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Neblio.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JSONRPCApi"/> class
        /// </summary>
        /// <returns></returns>
        public JSONRPCApi()
        {
            this.Configuration = Neblio.API.Client.Configuration.Default;

            ExceptionFactory = Neblio.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JSONRPCApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public JSONRPCApi(Neblio.API.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Neblio.API.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Neblio.API.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Neblio.API.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Neblio.API.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </summary>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>RpcResponse</returns>
        public RpcResponse RPC (RpcRequest rpcRequest)
        {
             ApiResponse<RpcResponse> localVarResponse = RPCWithHttpInfo(rpcRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </summary>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>ApiResponse of RpcResponse</returns>
        public ApiResponse< RpcResponse > RPCWithHttpInfo (RpcRequest rpcRequest)
        {
            // verify the required parameter 'rpcRequest' is set
            if (rpcRequest == null)
                throw new ApiException(400, "Missing required parameter 'rpcRequest' when calling JSONRPCApi->RPC");

            var localVarPath = "/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rpcRequest != null && rpcRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(rpcRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = rpcRequest; // byte array
            }

            // authentication (rpcAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RPC", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RpcResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RpcResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RpcResponse)));
        }

        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </summary>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>Task of RpcResponse</returns>
        public async System.Threading.Tasks.Task<RpcResponse> RPCAsync (RpcRequest rpcRequest)
        {
             ApiResponse<RpcResponse> localVarResponse = await RPCAsyncWithHttpInfo(rpcRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Send a JSON-RPC call to a localhost neblio-Qt or nebliod node Call any Neblio RPC command from the Neblio API libraries. Useful for signing transactions with a local node and other functions. Will not work from this page due to CORS restrictions. Requires a node to be running locally at 127.0.0.1 - Use port 16326 for testnet.
        /// </summary>
        /// <exception cref="Neblio.API.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rpcRequest"></param>
        /// <returns>Task of ApiResponse (RpcResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RpcResponse>> RPCAsyncWithHttpInfo (RpcRequest rpcRequest)
        {
            // verify the required parameter 'rpcRequest' is set
            if (rpcRequest == null)
                throw new ApiException(400, "Missing required parameter 'rpcRequest' when calling JSONRPCApi->RPC");

            var localVarPath = "/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (rpcRequest != null && rpcRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(rpcRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = rpcRequest; // byte array
            }

            // authentication (rpcAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RPC", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RpcResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (RpcResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RpcResponse)));
        }

    }
}
