/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Neblio.API.Client.OpenAPIDateConverter;

namespace Neblio.API.Model
{
    /// <summary>
    /// GetAddressInfoResponse
    /// </summary>
    [DataContract]
    public partial class GetAddressInfoResponse :  IEquatable<GetAddressInfoResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAddressInfoResponse" /> class.
        /// </summary>
        /// <param name="address">The Neblio Address.</param>
        /// <param name="utxos">Array of UTXOs held at this address..</param>
        public GetAddressInfoResponse(string address = default(string), List<GetAddressInfoResponseUtxos> utxos = default(List<GetAddressInfoResponseUtxos>))
        {
            this.Address = address;
            this.Utxos = utxos;
        }
        
        /// <summary>
        /// The Neblio Address
        /// </summary>
        /// <value>The Neblio Address</value>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// Array of UTXOs held at this address.
        /// </summary>
        /// <value>Array of UTXOs held at this address.</value>
        [DataMember(Name="utxos", EmitDefaultValue=false)]
        public List<GetAddressInfoResponseUtxos> Utxos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAddressInfoResponse {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Utxos: ").Append(Utxos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAddressInfoResponse);
        }

        /// <summary>
        /// Returns true if GetAddressInfoResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAddressInfoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAddressInfoResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Utxos == input.Utxos ||
                    this.Utxos != null &&
                    this.Utxos.SequenceEqual(input.Utxos)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.Utxos != null)
                    hashCode = hashCode * 59 + this.Utxos.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
