/* 
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITestnetFaucetApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Withdraws testnet NEBL to the specified address
        /// </summary>
        /// <remarks>
        /// Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>GetFaucetResponse</returns>
        GetFaucetResponse TestnetGetFaucet (string address, decimal? amount = null);

        /// <summary>
        /// Withdraws testnet NEBL to the specified address
        /// </summary>
        /// <remarks>
        /// Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>ApiResponse of GetFaucetResponse</returns>
        ApiResponse<GetFaucetResponse> TestnetGetFaucetWithHttpInfo (string address, decimal? amount = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Withdraws testnet NEBL to the specified address
        /// </summary>
        /// <remarks>
        /// Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>Task of GetFaucetResponse</returns>
        System.Threading.Tasks.Task<GetFaucetResponse> TestnetGetFaucetAsync (string address, decimal? amount = null);

        /// <summary>
        /// Withdraws testnet NEBL to the specified address
        /// </summary>
        /// <remarks>
        /// Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>Task of ApiResponse (GetFaucetResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetFaucetResponse>> TestnetGetFaucetAsyncWithHttpInfo (string address, decimal? amount = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TestnetFaucetApi : ITestnetFaucetApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TestnetFaucetApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TestnetFaucetApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TestnetFaucetApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TestnetFaucetApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Withdraws testnet NEBL to the specified address Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>GetFaucetResponse</returns>
        public GetFaucetResponse TestnetGetFaucet (string address, decimal? amount = null)
        {
             ApiResponse<GetFaucetResponse> localVarResponse = TestnetGetFaucetWithHttpInfo(address, amount);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Withdraws testnet NEBL to the specified address Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>ApiResponse of GetFaucetResponse</returns>
        public ApiResponse< GetFaucetResponse > TestnetGetFaucetWithHttpInfo (string address, decimal? amount = null)
        {
            // verify the required parameter 'address' is set
            if (address == null)
                throw new ApiException(400, "Missing required parameter 'address' when calling TestnetFaucetApi->TestnetGetFaucet");

            var localVarPath = "/testnet/faucet";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (address != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "address", address)); // query parameter
            if (amount != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "amount", amount)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TestnetGetFaucet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetFaucetResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetFaucetResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetFaucetResponse)));
        }

        /// <summary>
        /// Withdraws testnet NEBL to the specified address Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>Task of GetFaucetResponse</returns>
        public async System.Threading.Tasks.Task<GetFaucetResponse> TestnetGetFaucetAsync (string address, decimal? amount = null)
        {
             ApiResponse<GetFaucetResponse> localVarResponse = await TestnetGetFaucetAsyncWithHttpInfo(address, amount);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Withdraws testnet NEBL to the specified address Withdraw testnet NEBL to your Neblio Testnet address. By default amount is 1500000000 or 15 NEBL and has a max of 50 NEBL. Only 2 withdrawals allowed per 24 hour period. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="address">Your Neblio Testnet Address</param>
        /// <param name="amount">Amount of NEBL to withdrawal in satoshis (optional)</param>
        /// <returns>Task of ApiResponse (GetFaucetResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetFaucetResponse>> TestnetGetFaucetAsyncWithHttpInfo (string address, decimal? amount = null)
        {
            // verify the required parameter 'address' is set
            if (address == null)
                throw new ApiException(400, "Missing required parameter 'address' when calling TestnetFaucetApi->TestnetGetFaucet");

            var localVarPath = "/testnet/faucet";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (address != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "address", address)); // query parameter
            if (amount != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "amount", amount)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TestnetGetFaucet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetFaucetResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetFaucetResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetFaucetResponse)));
        }

    }
}
